#!/bin/bash

# taken from http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/


NAME="estate"                                    # Name of the application
DJANGODIR=/home/dlete/development/estate_project/estate     # Django project directory
#SOCKFILE=/home/dlete/development/estate_project/run/gunicorn.sock  # we will communicte using this unix socket
VIRTUALENVDIR=/home/dlete/.virtualenvs/estate
USER=dlete                                      # the user to run as
GROUP=dlete                                     # the group to run as
NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=estate.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=estate.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $VIRTUALENVDIR/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
#RUNDIR=$(dirname $SOCKFILE)
#test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $VIRTUALENVDIR/bin/gunicorn -b 127.0.0.1:8010 ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug
#  --log-level=debug \
#  --bind= 127.0.0.1:8010

